### ISSUE TITLE
TypeError: 'path' is an invalid keyword argument for this function

### ISSUE THREAD

**Issue by emircetinmemis** [schlegelp/skeletor#32]
Upon using teasar skeletonization on Python 3.9.6, one faces the following error:

```

In [11]: eids = SG.get_eids(path=path, directed=False)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In [11], line 1
----> 1 eids = SG.get_eids(path=path, directed=False)

TypeError: 'path' is an invalid keyword argument for this function

```

Any workaround one may know, apart from upgrading the Python version?

**Comment by schlegelp** [comment]
This is likely a problem with `igraph` not your Python version. Could you please check what version of `igraph` you have?

```python
>>> import igraph as ig
>>> ig.__version__
'0.10.1'
```

**Comment by schlegelp** [comment]
Actually I encountered another issue with graph `0.10.1` - I'd recommend using `0.9.11` for now.
